name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      
      - name: Dependecies
        run: npm ci
      
      - name: Build
        run: npm run build
        

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag sebastianmorales/rule
        
      - name: Push to Docker Hub
        run: docker push sebastianmorales/rule
        
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
        
      - name: Deploy VM
        run: |
          ./scripts/deployDocker.sh "{{ secrets.MY_PRIVATE_SSH_KEY }}"
        
